// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // File ini hanya dibaca Prisma CLI (db push, migrate, studio), bukan runtime aplikasi.
    // Runtime pakai DATABASE_URL lewat pg Pool di src/lib/prisma.ts.
    // CLI harus lewat koneksi langsung (port 5432): transaction pooler (pgbouncer=true,
    // port 6543) tidak mendukung prepared statement yang dipakai `db push`.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
